apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: pipeline-template
spec:
  params:
      description: The message to print
      default: This is the default message
      resourcetemplates:
      - apiVersion: tekton.dev/v1beta1
        kind: PipelineRun
        metadata:
          generateName: run-$(uid)
          labels:
            triggertemplated: "true"
            generatedBy: "triggers-example"
        spec:
          pipelineRef:
            name: kick-it-pipeline
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: simple-binding
spec:
  params: []            
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: manual-listener
spec:
  triggers:
    - binding:
        name: simple-binding
      template:
        name: pipeline-template
      params:
        - name: message
          value: Hello from the Manual Triggers EventListener!