apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: script-runner
spec:
  params:
    - name: message
      value: ${params.message}
  steps:
    - name: disk-info
      image: ubuntu
      command: ["bash", "-c"]
      args:
        - echo 'Getting some info';
          uname -a;
          whoami;
          pwd;
          ls -al;
          df -Th;
          ls -al /dev;
          ls -alR /var/run/secrets;
          df -h;